services:
  - type: web
    name: fightboat-frontend
    env: static
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000
    healthCheckPath: /
    autoDeploy: true 